// Server-free category labels so client components can import them.
export const CATEGORY_LABELS: Record<string, string> = {
  property_configuration: "Property configuration",
  property_class: "Property class",
  property_type: "Property type",
  property_status: "Property status",
  tenancy_class: "Tenancy class",
  property_tax: "Property tax",
  utility_type: "Utility type",
  tenancy_code: "Tenancy code",
  lease_status: "Lease status",
  payment_frequency: "Payment frequency",
  tenant_type: "Tenant type",
  tenant_status: "Tenant status",
  preferred_contact: "Preferred contact",
  nok_relationship: "Next-of-kin relationship",
  landlord_type: "Landlord type",
  invoice_status: "Invoice status",
  maintenance_status: "Maintenance status",
  maintenance_urgency: "Maintenance urgency",
  maintenance_type: "Maintenance type",
  key_status: "Key status",
  held_by_type: "Key held-by type",
  transaction_type: "Transaction type",
  transaction_category: "Transaction category",
  vat_rate: "VAT rate",
  supplier_type: "Supplier type",
  supplier_status: "Supplier status",
  document_linked_to: "Document linked-to",
  reminder_status: "Reminder status",
};
